git_dir: '/home/mcgaugheyd/git/scEiaD_modeling/'
prefix: 'hs111_mature_eye_20240924_full__NONneural_s6__'
ref_bcs: '/home/mcgaugheyd/git/scEiaD_modeling/data/hs111_mature_eye__stage4_NONneural_ref_bcs.20241001-02.csv.gz'
query_bcs: '/home/mcgaugheyd/git/scEiaD_modeling/data/hs111_mature_eye__stage4_NONneural_query_bcs.20241001-02.csv.gz'
epochs: ['200']
latent: ['30']
hvg: ['2000']
input_h5ad: '../hs111_mature_eye_20241121_full_2000hvg_200e_30l_stage6.h5ad'
scanvi_on: "hrCT"
scanvi_out: "hrCT_scANVI_step6"
pb_group: ['leiden3','hrCT_scANVI_step6', 'hrCT']
scib: False
continuous_covariate_keys: ''
